name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thank you for taking the time to submit an Issue!
          You should get a response to this issue within one to two days.
        pr-message: |
          Thank you for taking the time to submit a Pull Request!
          Please ensure the pull request is linked to an issue by using the commit format _Fixes <Issue #> - <Brief description of change>_.
