name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 18.4.0

    - name: Install dependencies
      run: npm install && npm run install-peers

    - name: Run tests
      run: npm test

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        config-file: ./.github/configs/codeql-config.yml

    - name: Perform build
      run: npm run build

    - name: Copy type definition to docs
      if: github.ref_name == 'master'
      run:  cp ./build/index.d.ts ./docs/

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2

    - name: Publish github pages docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref_name == 'master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

    - name: Publish to NPM if version has been updated
      uses: pascalgn/npm-publish-action@1.3.9
      if: github.event_name != 'pull_request'
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
